blank_issues_enabled: false
contact_links:
  - name: GitHub Community Support
    url: https://github.community/
    about: Please ask and answer questions here.
  - name: Admin Discussion Page
    url: https://github.com/orgs/Deck-of-Cards-Studio/teams/admin
    about: Or just yell at Parrotapocalypse about all the things he did wrong.
